version: '3.8'

services:
  # MongoDB database
  mongodb:
    image: mongo:5.0
    container_name: auracares_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  # Backend Node.js application
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: auracares_backend
    restart: always
    ports:
      - "5005:5005"
    environment:
      - NODE_ENV=development
      - PORT=5005
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/auracares?authSource=admin
      - JWT_SECRET=your-jwt-secret-key-change-in-production
      - GOOGLE_CLIENT_ID=your-google-client-id
      - GOOGLE_CLIENT_SECRET=your-google-client-secret
      - ML_SERVICE_URL=http://ml-service:5001
    depends_on:
      - mongodb
      - ml-service
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend React application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: auracares_frontend
    restart: always
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:5005/api
      - VITE_BASE_URL=http://localhost:5005
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  # Machine Learning Service
  ml-service:
    build:
      context: ./backend/ml-service
      dockerfile: Dockerfile
    container_name: auracares_ml_service
    restart: always
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1

volumes:
  mongodb_data: